FROM node:20.11.0-bookworm-slim AS build

WORKDIR /app

COPY strapi/package*.json ./
RUN npm ci

COPY strapi/ ./
RUN npm run build
RUN npm prune --omit=dev

FROM node:20.11.0-bookworm-slim

WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app ./
RUN chmod +x scripts/fly-start.sh

CMD ["sh", "scripts/fly-start.sh"]
